name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build_${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.400
            8.0.x
          
      - name: Define VERSION
        run: |
          echo "COMMIT=${GITHUB_SHA:0:7}"
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}"
          echo "BRANCH=${GITHUB_REF##*/}"
          
      - name: Build (Debug)
        run: dotnet build -c Debug

      - name: Test (Debug)
        run: dotnet test -c Debug -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          
      - name: Build (Release)
        run: dotnet build -c Release
        
      - name: Test (Release)
        run: dotnet test -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
        
      - name: Upload Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
        
